# Generated by Django 5.2.1 on 2025-05-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_infraction_commune_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couppoing',
            options={},
        ),
        migrations.AlterModelOptions(
            name='descente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patrouille',
            options={},
        ),
        migrations.AlterModelOptions(
            name='raffle',
            options={},
        ),
        migrations.AddField(
            model_name='couppoing',
            name='charettes_pouspous',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='couppoing',
            name='mendiants_interpelles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='couppoing',
            name='objet_saisie',
            field=models.CharField(blank=True, choices=[('Drogue', 'Drogue'), ('Arme Blanche', 'Arme Blanche'), ('Autres', 'Autres')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='couppoing',
            name='personne_interpellees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='descente',
            name='charettes_pouspous',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='descente',
            name='mendiants_interpelles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='descente',
            name='objet_saisie',
            field=models.CharField(blank=True, choices=[('Drogue', 'Drogue'), ('Arme Blanche', 'Arme Blanche'), ('Autres', 'Autres')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='descente',
            name='personne_interpellees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patrouille',
            name='charettes_pouspous',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patrouille',
            name='mendiants_interpelles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patrouille',
            name='objet_saisie',
            field=models.CharField(blank=True, choices=[('Drogue', 'Drogue'), ('Arme Blanche', 'Arme Blanche'), ('Autres', 'Autres')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patrouille',
            name='personne_interpellees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='raffle',
            name='charettes_pouspous',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='raffle',
            name='mendiants_interpelles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='raffle',
            name='objet_saisie',
            field=models.CharField(blank=True, choices=[('Drogue', 'Drogue'), ('Arme Blanche', 'Arme Blanche'), ('Autres', 'Autres')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='raffle',
            name='personne_interpellees',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
