# Generated by Django 5.2.1 on 2025-05-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_couppoing_options_alter_descente_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autresaisie',
            name='femmes',
        ),
        migrations.RemoveField(
            model_name='autresaisie',
            name='hommes',
        ),
        migrations.RemoveField(
            model_name='autresaisie',
            name='mineurs',
        ),
        migrations.RemoveField(
            model_name='saisiedrogue',
            name='femmes',
        ),
        migrations.RemoveField(
            model_name='saisiedrogue',
            name='hommes',
        ),
        migrations.RemoveField(
            model_name='saisiedrogue',
            name='mineurs',
        ),
    ]
