# Generated by Django 5.2.1 on 2025-05-22 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_remove_autresaisie_femmes_remove_autresaisie_hommes_and_more'),
        ('units', '0003_alter_activitygroup_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleRoutier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brouillon', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_controle', models.DateField()),
                ('motif', models.CharField(max_length=255)),
                ('nbre_motos', models.IntegerField(default=0)),
                ('nbre_autos', models.IntegerField(default=0)),
                ('nbre_tricycles', models.IntegerField(default=0)),
                ('observation', models.TextField(blank=True, null=True)),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.unite')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
