# Generated by Django 5.2.1 on 2025-05-14 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(choices=[('administratif', 'Administratif'), ('circulation', 'Circulation'), ('judiciaire', 'Judiciaire'), ('disposition', 'Mise à disposition'), ('operation', 'operation spécifiques'), ('constat', 'Accident de la Ciculaion'), ('rh', 'Ressources Humaines')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('cp', 'Commissariat de Police'), ('csp', 'Commissariat Special de Police'), ('pp', 'Poste de Police'), ('ui', 'Unité d’Intervention'), ('constat', 'Service Constat'), ('upr', 'Unité de Police Routiere')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='enfants', to='units.unite')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='UniteActivityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='units.activitygroup')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='units.unite')),
            ],
            options={
                'unique_together': {('unite', 'group')},
            },
        ),
    ]
