# Generated by Django 5.2.1 on 2025-05-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_alter_activitygroup_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitygroup',
            name='categorie',
            field=models.CharField(choices=[('administratif', 'Administratif'), ('circulation', 'Circulation'), ('judiciaire', 'Judiciaire'), ('disposition', 'Disposition'), ('operation', 'Operation'), ('constat', 'Accident de la Ciculaion'), ('rh', 'Ressources Humaines')], max_length=20),
        ),
    ]
