# Generated by Django 5.2.1 on 2025-05-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_alter_activitygroup_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitygroup',
            name='categorie',
            field=models.CharField(choices=[('administratif', 'Administratif'), ('circulation', 'Circulation'), ('judiciaire', 'Judiciaire'), ('disposition', 'Disposition'), ('operation', 'Operation'), ('constat', 'Accident de la Ciculaion'), ('rh', 'Ressources Humaines'), ('spja', 'SPJA')], max_length=20),
        ),
    ]
